return {
    CELL_HEIGHT = 32,
    CELL_WIDTH = 32,
    PLAYER_HEIGHT = 18,
    PLAYER_WIDTH = 22,
    SAW_HEIGHT = 24,
    SAW_WIDTH = 24,
    SPIKE_HEIGHT = 10,
    SPIKE_WIDTH = 26,
    GRAVITY = 250,
    JUMP_DECAY = 600,
    JUMP_ACCEL = 535,
    JUMP_BUMP_HEAD_DECAY_MODIFIER = 100,
    WALK_SPEED = 175,
    FRICTION = 800,
    AIR_CONTROL_SPEED = 150,
    UPGRADE_PICKUP_KEY = "e", --hack woooo
    UPGRADE_SPEED_GROUND_MULTIPLIER = 1.6,
    UPGRADE_SPEED_AIR_MULTIPLIER = 1.5,
    HEALTH_BASE = 9,
    INVULNERABILITY_DURATION = 1.25,
    INVULNERABILITY_FLASH_INTERVAL = 0.2,
    HEART_LOSS_FLASH_INTERVAL = 0.15,
    COLOURS = {
        WARNING = {1, 0, 0, 0.8},
        ACQUIRE_UPGRADE = {0, 0, 0, 1}
    },
    COST_JUMP = 1,
    COST_DOUBLE_JUMP = 2,
    COST_SPEED_BOOST = 3,
    COST_AIR_DASH = 3
}
