return {
    CELL_HEIGHT = 32,
    CELL_WIDTH = 32,
    PLAYER_HEIGHT = 24,
    PLAYER_WIDTH = 32,
    GRAVITY = 250,
    JUMP_DECAY = 600,
    JUMP_ACCEL = 520,
    JUMP_BUMP_HEAD_DECAY_MODIFIER = 10,
    WALK_SPEED = 175,
    FRICTION = 800,
    AIR_CONTROL_SPEED = 150,
    UPGRADE_PICKUP_KEY = "e", --hack woooo
    UPGRADE_SPEED_GROUND_MULTIPLIER = 1.6,
    UPGRADE_SPEED_AIR_MULTIPLIER = 1.5,
    HEALTH_BASE = 9,
    INVULNERABILITY_DURATION = 1.25,
    INVULNERABILITY_FLASH_INTERVAL = 0.2,
    COLOURS = {
        WARNING = {1, 0, 0, 0.8},
        ACQUIRE_UPGRADE = {0, 0, 0, 1}
    }
}
